### ISSUE TITLE
can not install EWCE

### ISSUE THREAD

**Issue by BioEpi** [NathanSkene/EWCE#33] opened 2021-05-24 15:27 UTC
Hello,
    I try to install EWCE following this page (https://nathanskene.github.io/EWCE/articles/EWCE.html), but I got the following errors:
Error: package or namespace load failed for ‘RNOmni’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/nas/longleaf/home/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-RNOmni/00new/RNOmni/libs/RNOmni.so':
  /nas/longleaf/apps/gcc/6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /nas/longleaf/home/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-RNOmni/00new/RNOmni/libs/RNOmni.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/nas/longleaf/home/R/x86_64-pc-linux-gnu-library/4.0/RNOmni’

The downloaded source packages are in
	‘/tmp/RtmpdPeehs/downloaded_packages’
✔  checking for file ‘/tmp/RtmpdPeehs/remotes74cba85791/neurogenomics-EWCE-793daf3/DESCRIPTION’ ...
─  preparing ‘EWCE’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘EWCE_0.99.2.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   
Installing package into ‘/nas/longleaf/home/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
ERROR: dependency ‘RNOmni’ is not available for package ‘EWCE’
* removing ‘/nas/longleaf/home/R/x86_64-pc-linux-gnu-library/4.0/EWCE’
Warning messages:
1: In i.p(...) : installation of package ‘RNOmni’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/tmp/RtmpdPeehs/file74cb713b194/EWCE_0.99.2.tar.gz’ had non-zero exit status

**Comment by Al-Murphy** [comment] 2021-05-24 17:53
Hey, 

What OS and R version are you using? We haven't noted an issue installing this before, could you also send the R code you used to install EWCE?

At a glance it looks like the issue is installing `RNOmni` rather than `EWCE` so perhaps try install that package and if your issue is there it may be better to get in contact with the `RNOmni` maintainers.

Thanks,
Alan.

**Comment by Al-Murphy** [comment] 2021-07-22 14:19
Closing until further information is received

**Closed by Al-Murphy** 2021-07-22 14:19 UTC
